POST http://localhost:5000/auth/signup
Content-Type: application/json

{
  "fullName": "Mohamed Nader",
  "email": "Mohamed.designer@example.com",
  "password": "mohamed123",
  "phoneNumber": "+1122113344",
  "city": "Cairo",
  "address": "Giza Haram",
  "isAdmin": false,
  "isDesigner": true
}