# POST http://localhost:5000/users
# Content-Type: application/json

# {
#   "fullName": "Mohamed Nader",
#   "email": "Mohamed.useddr@example.com",
#   "password": "mohamed123",
#   "phoneNumber": "+1122113344",
#   "city": "Cairo",
#   "address": "Giza Haram",
#   "isAdmin": false,
#   "isDesigner": false
# }

#Do not use it, use the SignUp function from the auth service